seo
geops/website pull request #180
Opened 2021-05-27 08:27 UTC by vanbeh

2021-05-27 08:53 UTC, friedjoff approved these changes

2021-07-05 08:34 UTC, friedjoff requested changes

2021-07-05 08:34 UTC, friedjoff commented on components/Teaser.js
> +  let teaserTitle = "";
How about using a `toptitle` string prop for `h1`?

2023-04-12 13:52 UTC, oterral commented
@friedjoff  is this  still worth it ?

2023-07-31 07:31 UTC, closed without merging